[package]
name = "bevy_2d_fsm_anims_macros"
description = "Derive macros for bevy_2d_fsm_anims"
version = "0.10.0"
edition = "2021"
authors = ["Mark Pekala <mfpekala@gmail.com>"]

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
